version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map Vite's dev server port
    volumes:
      - ./frontend:/usr/apnawakil/frontend # Enable live-reload with volume binding
      - /usr/apnawakil/frontend/node_modules # Prevent overwriting node_modules
    stdin_open: true # Allow live-reload
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Fixes issues with file watching in Docker
    command: ["npm", "run", "dev"] # Command to run Vite dev server

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map backend server port
    volumes:
      - ./backend:/usr/apnawakil/backend # Enable live-reload with volume binding
      - /usr/apnawakil/backend/node_modules # Prevent overwriting node_modules
    command: ["npm", "run", "dev"] # Command to run the backend dev server
